// ignore_for_file: non_constant_identifier_names, prefer_const_literals_to_create_immutables, prefer_const_constructors, unnecessary_string_interpolations, must_be_immutable

import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../../../controller/data_controller/data_controller.dart';

class F061 extends StatelessWidget {
  var f061Controller = Get.put(F061Controller());

  F061({super.key});

  @override
  Widget build(BuildContext context) {
    return GetBuilder<F061Controller>(
      builder: (_) => Scaffold(
          body: SingleChildScrollView(
        child: Center(
          child: Padding(
            padding: const EdgeInsets.all(10),
            child: Column(
              children: [
                Table(
                    columnWidths: {
                      0: FlexColumnWidth(1),
                      1: FlexColumnWidth(1),
                      2: FlexColumnWidth(1),
                      3: FlexColumnWidth(6.25),
                      4: FlexColumnWidth(1),
                    },
                    border: TableBorder.all(),
                    children: [
                      TableRow(children: [
                        TitleText(
                          "STAFF NAME",
                        ),
                        TitleText(
                          "BADGE",
                        ),
                        TitleText(
                          "POSITION",
                        ),
                        TitleText(
                          "GRADE",
                        ),
                        TitleText(
                          "AVERAGE",
                        ),
                      ]),
                    ]),
                Table(
                  columnWidths: {
                    0: FlexColumnWidth(1),
                    1: FlexColumnWidth(1),
                    2: FlexColumnWidth(1),
                    3: FlexColumnWidth(.25),
                    4: FlexColumnWidth(.25),
                    5: FlexColumnWidth(.25),
                    6: FlexColumnWidth(.25),
                    7: FlexColumnWidth(.25),
                    8: FlexColumnWidth(.25),
                    9: FlexColumnWidth(.25),
                    10: FlexColumnWidth(.25),
                    11: FlexColumnWidth(.25),
                    12: FlexColumnWidth(.25),
                    13: FlexColumnWidth(.25),
                    14: FlexColumnWidth(.25),
                    15: FlexColumnWidth(.25),
                    16: FlexColumnWidth(.25),
                    17: FlexColumnWidth(.25),
                    18: FlexColumnWidth(.25),
                    19: FlexColumnWidth(.25),
                    20: FlexColumnWidth(.25),
                    21: FlexColumnWidth(.25),
                    22: FlexColumnWidth(.25),
                    23: FlexColumnWidth(.25),
                    24: FlexColumnWidth(.25),
                    25: FlexColumnWidth(.25),
                    26: FlexColumnWidth(.25),
                    27: FlexColumnWidth(.25),
                    28: FlexColumnWidth(1),
                  },
                  border: TableBorder.all(),
                  children: [
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller1,
                      controllerbadge: f061Controller.text_Controller2,
                      color: Color(0xffFFFF00),
                      controllerposition: f061Controller.text_Controller27,
                      controllergrade1: f061Controller.text_Controller82,
                      controllergrade2: f061Controller.text_Controller109,
                      controllergrade3: f061Controller.text_Controller136,
                      controllergrade4: f061Controller.text_Controller163,
                      controllergrade5: f061Controller.text_Controller190,
                      controllergrade6: f061Controller.text_Controller217,
                      controllergrade7: f061Controller.text_Controller244,
                      controllergrade8: f061Controller.text_Controller271,
                      controllergrade9: f061Controller.text_Controller298,
                      controllergrade10: f061Controller.text_Controller324,
                      controllergrade11: f061Controller.text_Controller351,
                      controllergrade12: f061Controller.text_Controller378,
                      controllergrade13: f061Controller.text_Controller405,
                      controllergrade14: f061Controller.text_Controller434,
                      controllergrade15: f061Controller.text_Controller461,
                      controllergrade16: f061Controller.text_Controller488,
                      controllergrade17: f061Controller.text_Controller515,
                      controllergrade18: f061Controller.text_Controller542,
                      controllergrade19: f061Controller.text_Controller569,
                      controllergrade20: f061Controller.text_Controller596,
                      controllergrade21: f061Controller.text_Controller623,
                      controllergrade22: f061Controller.text_Controller650,
                      controllergrade23: f061Controller.text_Controller677,
                      controllergrade24: f061Controller.text_Controller704,
                      controllergrade25: f061Controller.text_Controller731,
                      controlleraverage: f061Controller.text_Controller758,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller3,
                      controllerbadge: f061Controller.text_Controller4,
                      color: Color(0xffE6B9B8),
                      controllerposition: f061Controller.text_Controller28,
                      controllergrade1: f061Controller.text_Controller83,
                      controllergrade2: f061Controller.text_Controller110,
                      controllergrade3: f061Controller.text_Controller137,
                      controllergrade4: f061Controller.text_Controller164,
                      controllergrade5: f061Controller.text_Controller191,
                      controllergrade6: f061Controller.text_Controller218,
                      controllergrade7: f061Controller.text_Controller245,
                      controllergrade8: f061Controller.text_Controller272,
                      controllergrade9: f061Controller.text_Controller299,
                      controllergrade10: f061Controller.text_Controller325,
                      controllergrade11: f061Controller.text_Controller352,
                      controllergrade12: f061Controller.text_Controller379,
                      controllergrade13: f061Controller.text_Controller406,
                      controllergrade14: f061Controller.text_Controller435,
                      controllergrade15: f061Controller.text_Controller462,
                      controllergrade16: f061Controller.text_Controller489,
                      controllergrade17: f061Controller.text_Controller516,
                      controllergrade18: f061Controller.text_Controller543,
                      controllergrade19: f061Controller.text_Controller570,
                      controllergrade20: f061Controller.text_Controller597,
                      controllergrade21: f061Controller.text_Controller624,
                      controllergrade22: f061Controller.text_Controller651,
                      controllergrade23: f061Controller.text_Controller678,
                      controllergrade24: f061Controller.text_Controller705,
                      controllergrade25: f061Controller.text_Controller732,
                      controlleraverage: f061Controller.text_Controller759,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller5,
                      controllerbadge: f061Controller.text_Controller6,
                      color: Color(0xffB9CDE5),
                      controllerposition: f061Controller.text_Controller29,
                      controllergrade1: f061Controller.text_Controller84,
                      controllergrade2: f061Controller.text_Controller111,
                      controllergrade3: f061Controller.text_Controller138,
                      controllergrade4: f061Controller.text_Controller165,
                      controllergrade5: f061Controller.text_Controller192,
                      controllergrade6: f061Controller.text_Controller219,
                      controllergrade7: f061Controller.text_Controller246,
                      controllergrade8: f061Controller.text_Controller273,
                      controllergrade9: f061Controller.text_Controller300,
                      controllergrade10: f061Controller.text_Controller326,
                      controllergrade11: f061Controller.text_Controller353,
                      controllergrade12: f061Controller.text_Controller380,
                      controllergrade13: f061Controller.text_Controller407,
                      controllergrade14: f061Controller.text_Controller436,
                      controllergrade15: f061Controller.text_Controller463,
                      controllergrade16: f061Controller.text_Controller490,
                      controllergrade17: f061Controller.text_Controller517,
                      controllergrade18: f061Controller.text_Controller544,
                      controllergrade19: f061Controller.text_Controller571,
                      controllergrade20: f061Controller.text_Controller598,
                      controllergrade21: f061Controller.text_Controller625,
                      controllergrade22: f061Controller.text_Controller652,
                      controllergrade23: f061Controller.text_Controller679,
                      controllergrade24: f061Controller.text_Controller706,
                      controllergrade25: f061Controller.text_Controller733,
                      controlleraverage: f061Controller.text_Controller760,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller7,
                      controllerbadge: f061Controller.text_Controller8,
                      color: Color(0xffB9CDE5),
                      controllerposition: f061Controller.text_Controller30,
                      controllergrade1: f061Controller.text_Controller85,
                      controllergrade2: f061Controller.text_Controller112,
                      controllergrade3: f061Controller.text_Controller139,
                      controllergrade4: f061Controller.text_Controller166,
                      controllergrade5: f061Controller.text_Controller193,
                      controllergrade6: f061Controller.text_Controller220,
                      controllergrade7: f061Controller.text_Controller247,
                      controllergrade8: f061Controller.text_Controller274,
                      controllergrade9: f061Controller.text_Controller301,
                      controllergrade10: f061Controller.text_Controller327,
                      controllergrade11: f061Controller.text_Controller354,
                      controllergrade12: f061Controller.text_Controller381,
                      controllergrade13: f061Controller.text_Controller408,
                      controllergrade14: f061Controller.text_Controller437,
                      controllergrade15: f061Controller.text_Controller464,
                      controllergrade16: f061Controller.text_Controller491,
                      controllergrade17: f061Controller.text_Controller518,
                      controllergrade18: f061Controller.text_Controller545,
                      controllergrade19: f061Controller.text_Controller572,
                      controllergrade20: f061Controller.text_Controller599,
                      controllergrade21: f061Controller.text_Controller626,
                      controllergrade22: f061Controller.text_Controller653,
                      controllergrade23: f061Controller.text_Controller680,
                      controllergrade24: f061Controller.text_Controller707,
                      controllergrade25: f061Controller.text_Controller734,
                      controlleraverage: f061Controller.text_Controller761,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller9,
                      controllerbadge: f061Controller.text_Controller81,
                      color: Color(0xffB9CDE5),
                      controllerposition: f061Controller.text_Controller10,
                      controllergrade1: f061Controller.text_Controller86,
                      controllergrade2: f061Controller.text_Controller113,
                      controllergrade3: f061Controller.text_Controller140,
                      controllergrade4: f061Controller.text_Controller167,
                      controllergrade5: f061Controller.text_Controller194,
                      controllergrade6: f061Controller.text_Controller221,
                      controllergrade7: f061Controller.text_Controller248,
                      controllergrade8: f061Controller.text_Controller275,
                      controllergrade9: f061Controller.text_Controller302,
                      controllergrade10: f061Controller.text_Controller328,
                      controllergrade11: f061Controller.text_Controller355,
                      controllergrade12: f061Controller.text_Controller382,
                      controllergrade13: f061Controller.text_Controller409,
                      controllergrade14: f061Controller.text_Controller438,
                      controllergrade15: f061Controller.text_Controller465,
                      controllergrade16: f061Controller.text_Controller492,
                      controllergrade17: f061Controller.text_Controller519,
                      controllergrade18: f061Controller.text_Controller546,
                      controllergrade19: f061Controller.text_Controller573,
                      controllergrade20: f061Controller.text_Controller600,
                      controllergrade21: f061Controller.text_Controller627,
                      controllergrade22: f061Controller.text_Controller654,
                      controllergrade23: f061Controller.text_Controller681,
                      controllergrade24: f061Controller.text_Controller708,
                      controllergrade25: f061Controller.text_Controller735,
                      controlleraverage: f061Controller.text_Controller762,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller11,
                      controllerbadge: f061Controller.text_Controller12,
                      color: Color(0xffFFFF00),
                      controllerposition: f061Controller.text_Controller32,
                      controllergrade1: f061Controller.text_Controller87,
                      controllergrade2: f061Controller.text_Controller114,
                      controllergrade3: f061Controller.text_Controller141,
                      controllergrade4: f061Controller.text_Controller168,
                      controllergrade5: f061Controller.text_Controller195,
                      controllergrade6: f061Controller.text_Controller222,
                      controllergrade7: f061Controller.text_Controller249,
                      controllergrade8: f061Controller.text_Controller276,
                      controllergrade9: f061Controller.text_Controller303,
                      controllergrade10: f061Controller.text_Controller329,
                      controllergrade11: f061Controller.text_Controller356,
                      controllergrade12: f061Controller.text_Controller383,
                      controllergrade13: f061Controller.text_Controller410,
                      controllergrade14: f061Controller.text_Controller439,
                      controllergrade15: f061Controller.text_Controller466,
                      controllergrade16: f061Controller.text_Controller493,
                      controllergrade17: f061Controller.text_Controller520,
                      controllergrade18: f061Controller.text_Controller547,
                      controllergrade19: f061Controller.text_Controller574,
                      controllergrade20: f061Controller.text_Controller601,
                      controllergrade21: f061Controller.text_Controller628,
                      controllergrade22: f061Controller.text_Controller655,
                      controllergrade23: f061Controller.text_Controller682,
                      controllergrade24: f061Controller.text_Controller709,
                      controllergrade25: f061Controller.text_Controller736,
                      controlleraverage: f061Controller.text_Controller763,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller13,
                      controllerbadge: f061Controller.text_Controller14,
                      color: Color(0xffE6B9B8),
                      controllerposition: f061Controller.text_Controller33,
                      controllergrade1: f061Controller.text_Controller88,
                      controllergrade2: f061Controller.text_Controller115,
                      controllergrade3: f061Controller.text_Controller142,
                      controllergrade4: f061Controller.text_Controller169,
                      controllergrade5: f061Controller.text_Controller196,
                      controllergrade6: f061Controller.text_Controller223,
                      controllergrade7: f061Controller.text_Controller250,
                      controllergrade8: f061Controller.text_Controller277,
                      controllergrade9: f061Controller.text_Controller304,
                      controllergrade10: f061Controller.text_Controller330,
                      controllergrade11: f061Controller.text_Controller357,
                      controllergrade12: f061Controller.text_Controller384,
                      controllergrade13: f061Controller.text_Controller411,
                      controllergrade14: f061Controller.text_Controller440,
                      controllergrade15: f061Controller.text_Controller467,
                      controllergrade16: f061Controller.text_Controller494,
                      controllergrade17: f061Controller.text_Controller521,
                      controllergrade18: f061Controller.text_Controller548,
                      controllergrade19: f061Controller.text_Controller575,
                      controllergrade20: f061Controller.text_Controller602,
                      controllergrade21: f061Controller.text_Controller629,
                      controllergrade22: f061Controller.text_Controller656,
                      controllergrade23: f061Controller.text_Controller683,
                      controllergrade24: f061Controller.text_Controller710,
                      controllergrade25: f061Controller.text_Controller737,
                      controlleraverage: f061Controller.text_Controller764,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller15,
                      controllerbadge: f061Controller.text_Controller16,
                      color: Color(0xffC3D69B),
                      controllerposition: f061Controller.text_Controller34,
                      controllergrade1: f061Controller.text_Controller89,
                      controllergrade2: f061Controller.text_Controller116,
                      controllergrade3: f061Controller.text_Controller143,
                      controllergrade4: f061Controller.text_Controller170,
                      controllergrade5: f061Controller.text_Controller197,
                      controllergrade6: f061Controller.text_Controller224,
                      controllergrade7: f061Controller.text_Controller251,
                      controllergrade8: f061Controller.text_Controller278,
                      controllergrade9: f061Controller.text_Controller305,
                      controllergrade10: f061Controller.text_Controller331,
                      controllergrade11: f061Controller.text_Controller358,
                      controllergrade12: f061Controller.text_Controller385,
                      controllergrade13: f061Controller.text_Controller412,
                      controllergrade14: f061Controller.text_Controller441,
                      controllergrade15: f061Controller.text_Controller468,
                      controllergrade16: f061Controller.text_Controller495,
                      controllergrade17: f061Controller.text_Controller522,
                      controllergrade18: f061Controller.text_Controller549,
                      controllergrade19: f061Controller.text_Controller576,
                      controllergrade20: f061Controller.text_Controller603,
                      controllergrade21: f061Controller.text_Controller630,
                      controllergrade22: f061Controller.text_Controller657,
                      controllergrade23: f061Controller.text_Controller684,
                      controllergrade24: f061Controller.text_Controller711,
                      controllergrade25: f061Controller.text_Controller738,
                      controlleraverage: f061Controller.text_Controller765,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller17,
                      controllerbadge: f061Controller.text_Controller18,
                      color: Color(0xffC3D69B),
                      controllerposition: f061Controller.text_Controller35,
                      controllergrade1: f061Controller.text_Controller90,
                      controllergrade2: f061Controller.text_Controller117,
                      controllergrade3: f061Controller.text_Controller144,
                      controllergrade4: f061Controller.text_Controller171,
                      controllergrade5: f061Controller.text_Controller198,
                      controllergrade6: f061Controller.text_Controller225,
                      controllergrade7: f061Controller.text_Controller252,
                      controllergrade8: f061Controller.text_Controller279,
                      controllergrade9: f061Controller.text_Controller306,
                      controllergrade10: f061Controller.text_Controller332,
                      controllergrade11: f061Controller.text_Controller359,
                      controllergrade12: f061Controller.text_Controller386,
                      controllergrade13: f061Controller.text_Controller413,
                      controllergrade14: f061Controller.text_Controller442,
                      controllergrade15: f061Controller.text_Controller469,
                      controllergrade16: f061Controller.text_Controller496,
                      controllergrade17: f061Controller.text_Controller523,
                      controllergrade18: f061Controller.text_Controller550,
                      controllergrade19: f061Controller.text_Controller577,
                      controllergrade20: f061Controller.text_Controller604,
                      controllergrade21: f061Controller.text_Controller631,
                      controllergrade22: f061Controller.text_Controller658,
                      controllergrade23: f061Controller.text_Controller685,
                      controllergrade24: f061Controller.text_Controller712,
                      controllergrade25: f061Controller.text_Controller739,
                      controlleraverage: f061Controller.text_Controller766,
                    ),
                  ],
                ),
                Table(
                    columnWidths: {
                      0: FlexColumnWidth(1),
                      1: FlexColumnWidth(1),
                      2: FlexColumnWidth(1),
                      3: FlexColumnWidth(6.25),
                      4: FlexColumnWidth(1),
                    },
                    border: TableBorder.all(),
                    children: [
                      TableRow(children: [
                        TitleText(
                          "STAFF NAME",
                        ),
                        TitleText(
                          "BADGE",
                        ),
                        TitleText(
                          "POSITION",
                        ),
                        TitleText(
                          "GRADE",
                        ),
                        TitleText(
                          "AVERAGE",
                        ),
                      ]),
                    ]),
                Table(
                  columnWidths: {
                    0: FlexColumnWidth(1),
                    1: FlexColumnWidth(1),
                    2: FlexColumnWidth(1),
                    3: FlexColumnWidth(.25),
                    4: FlexColumnWidth(.25),
                    5: FlexColumnWidth(.25),
                    6: FlexColumnWidth(.25),
                    7: FlexColumnWidth(.25),
                    8: FlexColumnWidth(.25),
                    9: FlexColumnWidth(.25),
                    10: FlexColumnWidth(.25),
                    11: FlexColumnWidth(.25),
                    12: FlexColumnWidth(.25),
                    13: FlexColumnWidth(.25),
                    14: FlexColumnWidth(.25),
                    15: FlexColumnWidth(.25),
                    16: FlexColumnWidth(.25),
                    17: FlexColumnWidth(.25),
                    18: FlexColumnWidth(.25),
                    19: FlexColumnWidth(.25),
                    20: FlexColumnWidth(.25),
                    21: FlexColumnWidth(.25),
                    22: FlexColumnWidth(.25),
                    23: FlexColumnWidth(.25),
                    24: FlexColumnWidth(.25),
                    25: FlexColumnWidth(.25),
                    26: FlexColumnWidth(.25),
                    27: FlexColumnWidth(.25),
                    28: FlexColumnWidth(1),
                  },
                  border: TableBorder.all(),
                  children: [
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller19,
                      controllerbadge: f061Controller.text_Controller20,
                      color: Color(0xffFFFF00),
                      controllerposition: f061Controller.text_Controller36,
                      controllergrade1: f061Controller.text_Controller91,
                      controllergrade2: f061Controller.text_Controller118,
                      controllergrade3: f061Controller.text_Controller145,
                      controllergrade4: f061Controller.text_Controller172,
                      controllergrade5: f061Controller.text_Controller199,
                      controllergrade6: f061Controller.text_Controller226,
                      controllergrade7: f061Controller.text_Controller253,
                      controllergrade8: f061Controller.text_Controller280,
                      controllergrade9: f061Controller.text_Controller307,
                      controllergrade10: f061Controller.text_Controller333,
                      controllergrade11: f061Controller.text_Controller360,
                      controllergrade12: f061Controller.text_Controller387,
                      controllergrade13: f061Controller.text_Controller414,
                      controllergrade14: f061Controller.text_Controller443,
                      controllergrade15: f061Controller.text_Controller470,
                      controllergrade16: f061Controller.text_Controller497,
                      controllergrade17: f061Controller.text_Controller524,
                      controllergrade18: f061Controller.text_Controller551,
                      controllergrade19: f061Controller.text_Controller578,
                      controllergrade20: f061Controller.text_Controller605,
                      controllergrade21: f061Controller.text_Controller632,
                      controllergrade22: f061Controller.text_Controller659,
                      controllergrade23: f061Controller.text_Controller686,
                      controllergrade24: f061Controller.text_Controller713,
                      controllergrade25: f061Controller.text_Controller740,
                      controlleraverage: f061Controller.text_Controller767,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller21,
                      controllerbadge: f061Controller.text_Controller22,
                      color: Color(0xffE6B9B8),
                      controllerposition: f061Controller.text_Controller37,
                      controllergrade1: f061Controller.text_Controller92,
                      controllergrade2: f061Controller.text_Controller119,
                      controllergrade3: f061Controller.text_Controller146,
                      controllergrade4: f061Controller.text_Controller173,
                      controllergrade5: f061Controller.text_Controller200,
                      controllergrade6: f061Controller.text_Controller227,
                      controllergrade7: f061Controller.text_Controller254,
                      controllergrade8: f061Controller.text_Controller281,
                      controllergrade9: f061Controller.text_Controller308,
                      controllergrade10: f061Controller.text_Controller334,
                      controllergrade11: f061Controller.text_Controller361,
                      controllergrade12: f061Controller.text_Controller388,
                      controllergrade13: f061Controller.text_Controller415,
                      controllergrade14: f061Controller.text_Controller444,
                      controllergrade15: f061Controller.text_Controller471,
                      controllergrade16: f061Controller.text_Controller498,
                      controllergrade17: f061Controller.text_Controller525,
                      controllergrade18: f061Controller.text_Controller552,
                      controllergrade19: f061Controller.text_Controller579,
                      controllergrade20: f061Controller.text_Controller606,
                      controllergrade21: f061Controller.text_Controller633,
                      controllergrade22: f061Controller.text_Controller660,
                      controllergrade23: f061Controller.text_Controller687,
                      controllergrade24: f061Controller.text_Controller714,
                      controllergrade25: f061Controller.text_Controller741,
                      controlleraverage: f061Controller.text_Controller768,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller23,
                      controllerbadge: f061Controller.text_Controller24,
                      color: Color(0xffB9CDE5),
                      controllerposition: f061Controller.text_Controller38,
                      controllergrade1: f061Controller.text_Controller93,
                      controllergrade2: f061Controller.text_Controller120,
                      controllergrade3: f061Controller.text_Controller147,
                      controllergrade4: f061Controller.text_Controller174,
                      controllergrade5: f061Controller.text_Controller201,
                      controllergrade6: f061Controller.text_Controller228,
                      controllergrade7: f061Controller.text_Controller255,
                      controllergrade8: f061Controller.text_Controller282,
                      controllergrade9: f061Controller.text_Controller309,
                      controllergrade10: f061Controller.text_Controller335,
                      controllergrade11: f061Controller.text_Controller362,
                      controllergrade12: f061Controller.text_Controller389,
                      controllergrade13: f061Controller.text_Controller416,
                      controllergrade14: f061Controller.text_Controller445,
                      controllergrade15: f061Controller.text_Controller472,
                      controllergrade16: f061Controller.text_Controller499,
                      controllergrade17: f061Controller.text_Controller526,
                      controllergrade18: f061Controller.text_Controller553,
                      controllergrade19: f061Controller.text_Controller580,
                      controllergrade20: f061Controller.text_Controller607,
                      controllergrade21: f061Controller.text_Controller634,
                      controllergrade22: f061Controller.text_Controller661,
                      controllergrade23: f061Controller.text_Controller688,
                      controllergrade24: f061Controller.text_Controller715,
                      controllergrade25: f061Controller.text_Controller742,
                      controlleraverage: f061Controller.text_Controller769,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller25,
                      controllerbadge: f061Controller.text_Controller26,
                      color: Color(0xffB9CDE5),
                      controllerposition: f061Controller.text_Controller39,
                      controllergrade1: f061Controller.text_Controller94,
                      controllergrade2: f061Controller.text_Controller121,
                      controllergrade3: f061Controller.text_Controller148,
                      controllergrade4: f061Controller.text_Controller175,
                      controllergrade5: f061Controller.text_Controller202,
                      controllergrade6: f061Controller.text_Controller229,
                      controllergrade7: f061Controller.text_Controller256,
                      controllergrade8: f061Controller.text_Controller283,
                      controllergrade9: f061Controller.text_Controller310,
                      controllergrade10: f061Controller.text_Controller336,
                      controllergrade11: f061Controller.text_Controller363,
                      controllergrade12: f061Controller.text_Controller390,
                      controllergrade13: f061Controller.text_Controller417,
                      controllergrade14: f061Controller.text_Controller446,
                      controllergrade15: f061Controller.text_Controller473,
                      controllergrade16: f061Controller.text_Controller500,
                      controllergrade17: f061Controller.text_Controller527,
                      controllergrade18: f061Controller.text_Controller554,
                      controllergrade19: f061Controller.text_Controller581,
                      controllergrade20: f061Controller.text_Controller608,
                      controllergrade21: f061Controller.text_Controller635,
                      controllergrade22: f061Controller.text_Controller662,
                      controllergrade23: f061Controller.text_Controller689,
                      controllergrade24: f061Controller.text_Controller716,
                      controllergrade25: f061Controller.text_Controller743,
                      controlleraverage: f061Controller.text_Controller770,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller54,
                      controllerbadge: f061Controller.text_Controller28,
                      color: Color(0xffB9CDE5),
                      controllerposition: f061Controller.text_Controller40,
                      controllergrade1: f061Controller.text_Controller95,
                      controllergrade2: f061Controller.text_Controller122,
                      controllergrade3: f061Controller.text_Controller149,
                      controllergrade4: f061Controller.text_Controller176,
                      controllergrade5: f061Controller.text_Controller203,
                      controllergrade6: f061Controller.text_Controller230,
                      controllergrade7: f061Controller.text_Controller257,
                      controllergrade8: f061Controller.text_Controller284,
                      controllergrade9: f061Controller.text_Controller311,
                      controllergrade10: f061Controller.text_Controller337,
                      controllergrade11: f061Controller.text_Controller364,
                      controllergrade12: f061Controller.text_Controller391,
                      controllergrade13: f061Controller.text_Controller418,
                      controllergrade14: f061Controller.text_Controller447,
                      controllergrade15: f061Controller.text_Controller474,
                      controllergrade16: f061Controller.text_Controller501,
                      controllergrade17: f061Controller.text_Controller528,
                      controllergrade18: f061Controller.text_Controller555,
                      controllergrade19: f061Controller.text_Controller582,
                      controllergrade20: f061Controller.text_Controller609,
                      controllergrade21: f061Controller.text_Controller636,
                      controllergrade22: f061Controller.text_Controller663,
                      controllergrade23: f061Controller.text_Controller690,
                      controllergrade24: f061Controller.text_Controller717,
                      controllergrade25: f061Controller.text_Controller744,
                      controlleraverage: f061Controller.text_Controller771,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller55,
                      controllerbadge: f061Controller.text_Controller56,
                      color: Color(0xffFFFF00),
                      controllerposition: f061Controller.text_Controller41,
                      controllergrade1: f061Controller.text_Controller96,
                      controllergrade2: f061Controller.text_Controller123,
                      controllergrade3: f061Controller.text_Controller150,
                      controllergrade4: f061Controller.text_Controller177,
                      controllergrade5: f061Controller.text_Controller204,
                      controllergrade6: f061Controller.text_Controller231,
                      controllergrade7: f061Controller.text_Controller258,
                      controllergrade8: f061Controller.text_Controller285,
                      controllergrade9: f061Controller.text_Controller312,
                      controllergrade10: f061Controller.text_Controller338,
                      controllergrade11: f061Controller.text_Controller365,
                      controllergrade12: f061Controller.text_Controller392,
                      controllergrade13: f061Controller.text_Controller419,
                      controllergrade14: f061Controller.text_Controller448,
                      controllergrade15: f061Controller.text_Controller475,
                      controllergrade16: f061Controller.text_Controller502,
                      controllergrade17: f061Controller.text_Controller529,
                      controllergrade18: f061Controller.text_Controller556,
                      controllergrade19: f061Controller.text_Controller583,
                      controllergrade20: f061Controller.text_Controller610,
                      controllergrade21: f061Controller.text_Controller637,
                      controllergrade22: f061Controller.text_Controller664,
                      controllergrade23: f061Controller.text_Controller691,
                      controllergrade24: f061Controller.text_Controller718,
                      controllergrade25: f061Controller.text_Controller745,
                      controlleraverage: f061Controller.text_Controller772,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller57,
                      controllerbadge: f061Controller.text_Controller58,
                      color: Color(0xffE6B9B8),
                      controllerposition: f061Controller.text_Controller42,
                      controllergrade1: f061Controller.text_Controller97,
                      controllergrade2: f061Controller.text_Controller124,
                      controllergrade3: f061Controller.text_Controller151,
                      controllergrade4: f061Controller.text_Controller178,
                      controllergrade5: f061Controller.text_Controller205,
                      controllergrade6: f061Controller.text_Controller232,
                      controllergrade7: f061Controller.text_Controller259,
                      controllergrade8: f061Controller.text_Controller286,
                      controllergrade9: f061Controller.text_Controller313,
                      controllergrade10: f061Controller.text_Controller339,
                      controllergrade11: f061Controller.text_Controller366,
                      controllergrade12: f061Controller.text_Controller393,
                      controllergrade13: f061Controller.text_Controller420,
                      controllergrade14: f061Controller.text_Controller449,
                      controllergrade15: f061Controller.text_Controller476,
                      controllergrade16: f061Controller.text_Controller503,
                      controllergrade17: f061Controller.text_Controller530,
                      controllergrade18: f061Controller.text_Controller557,
                      controllergrade19: f061Controller.text_Controller584,
                      controllergrade20: f061Controller.text_Controller611,
                      controllergrade21: f061Controller.text_Controller638,
                      controllergrade22: f061Controller.text_Controller665,
                      controllergrade23: f061Controller.text_Controller692,
                      controllergrade24: f061Controller.text_Controller719,
                      controllergrade25: f061Controller.text_Controller746,
                      controlleraverage: f061Controller.text_Controller773,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller59,
                      controllerbadge: f061Controller.text_Controller60,
                      color: Color(0xffC3D69B),
                      controllerposition: f061Controller.text_Controller43,
                      controllergrade1: f061Controller.text_Controller98,
                      controllergrade2: f061Controller.text_Controller125,
                      controllergrade3: f061Controller.text_Controller152,
                      controllergrade4: f061Controller.text_Controller179,
                      controllergrade5: f061Controller.text_Controller206,
                      controllergrade6: f061Controller.text_Controller233,
                      controllergrade7: f061Controller.text_Controller260,
                      controllergrade8: f061Controller.text_Controller287,
                      controllergrade9: f061Controller.text_Controller314,
                      controllergrade10: f061Controller.text_Controller340,
                      controllergrade11: f061Controller.text_Controller367,
                      controllergrade12: f061Controller.text_Controller394,
                      controllergrade13: f061Controller.text_Controller421,
                      controllergrade14: f061Controller.text_Controller450,
                      controllergrade15: f061Controller.text_Controller477,
                      controllergrade16: f061Controller.text_Controller504,
                      controllergrade17: f061Controller.text_Controller531,
                      controllergrade18: f061Controller.text_Controller558,
                      controllergrade19: f061Controller.text_Controller585,
                      controllergrade20: f061Controller.text_Controller612,
                      controllergrade21: f061Controller.text_Controller639,
                      controllergrade22: f061Controller.text_Controller666,
                      controllergrade23: f061Controller.text_Controller693,
                      controllergrade24: f061Controller.text_Controller720,
                      controllergrade25: f061Controller.text_Controller747,
                      controlleraverage: f061Controller.text_Controller774,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller61,
                      controllerbadge: f061Controller.text_Controller62,
                      color: Color(0xffC3D69B),
                      controllerposition: f061Controller.text_Controller44,
                      controllergrade1: f061Controller.text_Controller99,
                      controllergrade2: f061Controller.text_Controller126,
                      controllergrade3: f061Controller.text_Controller153,
                      controllergrade4: f061Controller.text_Controller180,
                      controllergrade5: f061Controller.text_Controller207,
                      controllergrade6: f061Controller.text_Controller234,
                      controllergrade7: f061Controller.text_Controller261,
                      controllergrade8: f061Controller.text_Controller288,
                      controllergrade9: f061Controller.text_Controller315,
                      controllergrade10: f061Controller.text_Controller341,
                      controllergrade11: f061Controller.text_Controller368,
                      controllergrade12: f061Controller.text_Controller395,
                      controllergrade13: f061Controller.text_Controller422,
                      controllergrade14: f061Controller.text_Controller451,
                      controllergrade15: f061Controller.text_Controller478,
                      controllergrade16: f061Controller.text_Controller505,
                      controllergrade17: f061Controller.text_Controller532,
                      controllergrade18: f061Controller.text_Controller559,
                      controllergrade19: f061Controller.text_Controller586,
                      controllergrade20: f061Controller.text_Controller613,
                      controllergrade21: f061Controller.text_Controller640,
                      controllergrade22: f061Controller.text_Controller667,
                      controllergrade23: f061Controller.text_Controller694,
                      controllergrade24: f061Controller.text_Controller721,
                      controllergrade25: f061Controller.text_Controller748,
                      controlleraverage: f061Controller.text_Controller775,
                    ),
                  ],
                ),
                Table(
                    columnWidths: {
                      0: FlexColumnWidth(1),
                      1: FlexColumnWidth(1),
                      2: FlexColumnWidth(1),
                      3: FlexColumnWidth(6.25),
                      4: FlexColumnWidth(1),
                    },
                    border: TableBorder.all(),
                    children: [
                      TableRow(children: [
                        TitleText(
                          "STAFF NAME",
                        ),
                        TitleText(
                          "BADGE",
                        ),
                        TitleText(
                          "POSITION",
                        ),
                        TitleText(
                          "GRADE",
                        ),
                        TitleText(
                          "AVERAGE",
                        ),
                      ]),
                    ]),
                Table(
                  columnWidths: {
                    0: FlexColumnWidth(1),
                    1: FlexColumnWidth(1),
                    2: FlexColumnWidth(1),
                    3: FlexColumnWidth(.25),
                    4: FlexColumnWidth(.25),
                    5: FlexColumnWidth(.25),
                    6: FlexColumnWidth(.25),
                    7: FlexColumnWidth(.25),
                    8: FlexColumnWidth(.25),
                    9: FlexColumnWidth(.25),
                    10: FlexColumnWidth(.25),
                    11: FlexColumnWidth(.25),
                    12: FlexColumnWidth(.25),
                    13: FlexColumnWidth(.25),
                    14: FlexColumnWidth(.25),
                    15: FlexColumnWidth(.25),
                    16: FlexColumnWidth(.25),
                    17: FlexColumnWidth(.25),
                    18: FlexColumnWidth(.25),
                    19: FlexColumnWidth(.25),
                    20: FlexColumnWidth(.25),
                    21: FlexColumnWidth(.25),
                    22: FlexColumnWidth(.25),
                    23: FlexColumnWidth(.25),
                    24: FlexColumnWidth(.25),
                    25: FlexColumnWidth(.25),
                    26: FlexColumnWidth(.25),
                    27: FlexColumnWidth(.25),
                    28: FlexColumnWidth(1),
                  },
                  border: TableBorder.all(),
                  children: [
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller63,
                      controllerbadge: f061Controller.text_Controller64,
                      color: Color(0xffFFFF00),
                      controllerposition: f061Controller.text_Controller45,
                      controllergrade1: f061Controller.text_Controller100,
                      controllergrade2: f061Controller.text_Controller127,
                      controllergrade3: f061Controller.text_Controller154,
                      controllergrade4: f061Controller.text_Controller181,
                      controllergrade5: f061Controller.text_Controller208,
                      controllergrade6: f061Controller.text_Controller235,
                      controllergrade7: f061Controller.text_Controller262,
                      controllergrade8: f061Controller.text_Controller289,
                      controllergrade9: f061Controller.text_Controller316,
                      controllergrade10: f061Controller.text_Controller342,
                      controllergrade11: f061Controller.text_Controller369,
                      controllergrade12: f061Controller.text_Controller396,
                      controllergrade13: f061Controller.text_Controller423,
                      controllergrade14: f061Controller.text_Controller452,
                      controllergrade15: f061Controller.text_Controller479,
                      controllergrade16: f061Controller.text_Controller506,
                      controllergrade17: f061Controller.text_Controller533,
                      controllergrade18: f061Controller.text_Controller560,
                      controllergrade19: f061Controller.text_Controller587,
                      controllergrade20: f061Controller.text_Controller614,
                      controllergrade21: f061Controller.text_Controller641,
                      controllergrade22: f061Controller.text_Controller668,
                      controllergrade23: f061Controller.text_Controller695,
                      controllergrade24: f061Controller.text_Controller722,
                      controllergrade25: f061Controller.text_Controller749,
                      controlleraverage: f061Controller.text_Controller776,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller65,
                      controllerbadge: f061Controller.text_Controller66,
                      color: Color(0xffE6B9B8),
                      controllerposition: f061Controller.text_Controller46,
                      controllergrade1: f061Controller.text_Controller101,
                      controllergrade2: f061Controller.text_Controller128,
                      controllergrade3: f061Controller.text_Controller155,
                      controllergrade4: f061Controller.text_Controller182,
                      controllergrade5: f061Controller.text_Controller209,
                      controllergrade6: f061Controller.text_Controller236,
                      controllergrade7: f061Controller.text_Controller263,
                      controllergrade8: f061Controller.text_Controller290,
                      controllergrade9: f061Controller.text_Controller317,
                      controllergrade10: f061Controller.text_Controller343,
                      controllergrade11: f061Controller.text_Controller370,
                      controllergrade12: f061Controller.text_Controller397,
                      controllergrade13: f061Controller.text_Controller424,
                      controllergrade14: f061Controller.text_Controller453,
                      controllergrade15: f061Controller.text_Controller480,
                      controllergrade16: f061Controller.text_Controller507,
                      controllergrade17: f061Controller.text_Controller534,
                      controllergrade18: f061Controller.text_Controller561,
                      controllergrade19: f061Controller.text_Controller588,
                      controllergrade20: f061Controller.text_Controller615,
                      controllergrade21: f061Controller.text_Controller642,
                      controllergrade22: f061Controller.text_Controller669,
                      controllergrade23: f061Controller.text_Controller696,
                      controllergrade24: f061Controller.text_Controller723,
                      controllergrade25: f061Controller.text_Controller750,
                      controlleraverage: f061Controller.text_Controller777,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller67,
                      controllerbadge: f061Controller.text_Controller68,
                      color: Color(0xffB9CDE5),
                      controllerposition: f061Controller.text_Controller47,
                      controllergrade1: f061Controller.text_Controller102,
                      controllergrade2: f061Controller.text_Controller129,
                      controllergrade3: f061Controller.text_Controller156,
                      controllergrade4: f061Controller.text_Controller183,
                      controllergrade5: f061Controller.text_Controller210,
                      controllergrade6: f061Controller.text_Controller237,
                      controllergrade7: f061Controller.text_Controller264,
                      controllergrade8: f061Controller.text_Controller291,
                      controllergrade9: f061Controller.text_Controller318,
                      controllergrade10: f061Controller.text_Controller344,
                      controllergrade11: f061Controller.text_Controller371,
                      controllergrade12: f061Controller.text_Controller398,
                      controllergrade13: f061Controller.text_Controller425,
                      controllergrade14: f061Controller.text_Controller454,
                      controllergrade15: f061Controller.text_Controller481,
                      controllergrade16: f061Controller.text_Controller508,
                      controllergrade17: f061Controller.text_Controller535,
                      controllergrade18: f061Controller.text_Controller562,
                      controllergrade19: f061Controller.text_Controller589,
                      controllergrade20: f061Controller.text_Controller616,
                      controllergrade21: f061Controller.text_Controller643,
                      controllergrade22: f061Controller.text_Controller670,
                      controllergrade23: f061Controller.text_Controller697,
                      controllergrade24: f061Controller.text_Controller724,
                      controllergrade25: f061Controller.text_Controller751,
                      controlleraverage: f061Controller.text_Controller778,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller69,
                      controllerbadge: f061Controller.text_Controller70,
                      color: Color(0xffB9CDE5),
                      controllerposition: f061Controller.text_Controller48,
                      controllergrade1: f061Controller.text_Controller103,
                      controllergrade2: f061Controller.text_Controller130,
                      controllergrade3: f061Controller.text_Controller157,
                      controllergrade4: f061Controller.text_Controller184,
                      controllergrade5: f061Controller.text_Controller211,
                      controllergrade6: f061Controller.text_Controller238,
                      controllergrade7: f061Controller.text_Controller265,
                      controllergrade8: f061Controller.text_Controller292,
                      controllergrade9: f061Controller.text_Controller319,
                      controllergrade10: f061Controller.text_Controller345,
                      controllergrade11: f061Controller.text_Controller372,
                      controllergrade12: f061Controller.text_Controller399,
                      controllergrade13: f061Controller.text_Controller426,
                      controllergrade14: f061Controller.text_Controller455,
                      controllergrade15: f061Controller.text_Controller482,
                      controllergrade16: f061Controller.text_Controller509,
                      controllergrade17: f061Controller.text_Controller536,
                      controllergrade18: f061Controller.text_Controller563,
                      controllergrade19: f061Controller.text_Controller590,
                      controllergrade20: f061Controller.text_Controller617,
                      controllergrade21: f061Controller.text_Controller644,
                      controllergrade22: f061Controller.text_Controller671,
                      controllergrade23: f061Controller.text_Controller698,
                      controllergrade24: f061Controller.text_Controller725,
                      controllergrade25: f061Controller.text_Controller752,
                      controlleraverage: f061Controller.text_Controller779,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller71,
                      controllerbadge: f061Controller.text_Controller72,
                      color: Color(0xffB9CDE5),
                      controllerposition: f061Controller.text_Controller49,
                      controllergrade1: f061Controller.text_Controller104,
                      controllergrade2: f061Controller.text_Controller131,
                      controllergrade3: f061Controller.text_Controller158,
                      controllergrade4: f061Controller.text_Controller185,
                      controllergrade5: f061Controller.text_Controller212,
                      controllergrade6: f061Controller.text_Controller239,
                      controllergrade7: f061Controller.text_Controller266,
                      controllergrade8: f061Controller.text_Controller293,
                      controllergrade9: f061Controller.text_Controller320,
                      controllergrade10: f061Controller.text_Controller346,
                      controllergrade11: f061Controller.text_Controller373,
                      controllergrade12: f061Controller.text_Controller400,
                      controllergrade13: f061Controller.text_Controller427,
                      controllergrade14: f061Controller.text_Controller456,
                      controllergrade15: f061Controller.text_Controller483,
                      controllergrade16: f061Controller.text_Controller510,
                      controllergrade17: f061Controller.text_Controller537,
                      controllergrade18: f061Controller.text_Controller564,
                      controllergrade19: f061Controller.text_Controller591,
                      controllergrade20: f061Controller.text_Controller618,
                      controllergrade21: f061Controller.text_Controller645,
                      controllergrade22: f061Controller.text_Controller672,
                      controllergrade23: f061Controller.text_Controller699,
                      controllergrade24: f061Controller.text_Controller726,
                      controllergrade25: f061Controller.text_Controller753,
                      controlleraverage: f061Controller.text_Controller780,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller73,
                      controllerbadge: f061Controller.text_Controller74,
                      color: Color(0xffFFFF00),
                      controllerposition: f061Controller.text_Controller50,
                      controllergrade1: f061Controller.text_Controller105,
                      controllergrade2: f061Controller.text_Controller132,
                      controllergrade3: f061Controller.text_Controller159,
                      controllergrade4: f061Controller.text_Controller186,
                      controllergrade5: f061Controller.text_Controller213,
                      controllergrade6: f061Controller.text_Controller240,
                      controllergrade7: f061Controller.text_Controller267,
                      controllergrade8: f061Controller.text_Controller294,
                      controllergrade9: f061Controller.text_Controller321,
                      controllergrade10: f061Controller.text_Controller347,
                      controllergrade11: f061Controller.text_Controller374,
                      controllergrade12: f061Controller.text_Controller401,
                      controllergrade13: f061Controller.text_Controller428,
                      controllergrade14: f061Controller.text_Controller457,
                      controllergrade15: f061Controller.text_Controller484,
                      controllergrade16: f061Controller.text_Controller511,
                      controllergrade17: f061Controller.text_Controller538,
                      controllergrade18: f061Controller.text_Controller565,
                      controllergrade19: f061Controller.text_Controller592,
                      controllergrade20: f061Controller.text_Controller619,
                      controllergrade21: f061Controller.text_Controller646,
                      controllergrade22: f061Controller.text_Controller673,
                      controllergrade23: f061Controller.text_Controller700,
                      controllergrade24: f061Controller.text_Controller727,
                      controllergrade25: f061Controller.text_Controller754,
                      controlleraverage: f061Controller.text_Controller781,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller75,
                      controllerbadge: f061Controller.text_Controller76,
                      color: Color(0xffE6B9B8),
                      controllerposition: f061Controller.text_Controller51,
                      controllergrade1: f061Controller.text_Controller106,
                      controllergrade2: f061Controller.text_Controller133,
                      controllergrade3: f061Controller.text_Controller160,
                      controllergrade4: f061Controller.text_Controller187,
                      controllergrade5: f061Controller.text_Controller214,
                      controllergrade6: f061Controller.text_Controller241,
                      controllergrade7: f061Controller.text_Controller268,
                      controllergrade8: f061Controller.text_Controller295,
                      controllergrade9: f061Controller.text_Controller322,
                      controllergrade10: f061Controller.text_Controller348,
                      controllergrade11: f061Controller.text_Controller375,
                      controllergrade12: f061Controller.text_Controller402,
                      controllergrade13: f061Controller.text_Controller429,
                      controllergrade14: f061Controller.text_Controller458,
                      controllergrade15: f061Controller.text_Controller485,
                      controllergrade16: f061Controller.text_Controller512,
                      controllergrade17: f061Controller.text_Controller539,
                      controllergrade18: f061Controller.text_Controller566,
                      controllergrade19: f061Controller.text_Controller593,
                      controllergrade20: f061Controller.text_Controller620,
                      controllergrade21: f061Controller.text_Controller647,
                      controllergrade22: f061Controller.text_Controller674,
                      controllergrade23: f061Controller.text_Controller701,
                      controllergrade24: f061Controller.text_Controller728,
                      controllergrade25: f061Controller.text_Controller755,
                      controlleraverage: f061Controller.text_Controller782,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller77,
                      controllerbadge: f061Controller.text_Controller78,
                      color: Color(0xffC3D69B),
                      controllerposition: f061Controller.text_Controller52,
                      controllergrade1: f061Controller.text_Controller107,
                      controllergrade2: f061Controller.text_Controller134,
                      controllergrade3: f061Controller.text_Controller161,
                      controllergrade4: f061Controller.text_Controller188,
                      controllergrade5: f061Controller.text_Controller215,
                      controllergrade6: f061Controller.text_Controller242,
                      controllergrade7: f061Controller.text_Controller269,
                      controllergrade8: f061Controller.text_Controller296,
                      controllergrade9: f061Controller.text_Controller323,
                      controllergrade10: f061Controller.text_Controller349,
                      controllergrade11: f061Controller.text_Controller376,
                      controllergrade12: f061Controller.text_Controller403,
                      controllergrade13: f061Controller.text_Controller430,
                      controllergrade14: f061Controller.text_Controller459,
                      controllergrade15: f061Controller.text_Controller486,
                      controllergrade16: f061Controller.text_Controller513,
                      controllergrade17: f061Controller.text_Controller540,
                      controllergrade18: f061Controller.text_Controller567,
                      controllergrade19: f061Controller.text_Controller594,
                      controllergrade20: f061Controller.text_Controller621,
                      controllergrade21: f061Controller.text_Controller648,
                      controllergrade22: f061Controller.text_Controller675,
                      controllergrade23: f061Controller.text_Controller702,
                      controllergrade24: f061Controller.text_Controller729,
                      controllergrade25: f061Controller.text_Controller756,
                      controlleraverage: f061Controller.text_Controller783,
                    ),
                    buildRowWidget(
                      controllerstaff: f061Controller.text_Controller79,
                      controllerbadge: f061Controller.text_Controller80,
                      color: Color(0xffC3D69B),
                      controllerposition: f061Controller.text_Controller53,
                      controllergrade1: f061Controller.text_Controller108,
                      controllergrade2: f061Controller.text_Controller135,
                      controllergrade3: f061Controller.text_Controller162,
                      controllergrade4: f061Controller.text_Controller189,
                      controllergrade5: f061Controller.text_Controller216,
                      controllergrade6: f061Controller.text_Controller243,
                      controllergrade7: f061Controller.text_Controller270,
                      controllergrade8: f061Controller.text_Controller297,
                      controllergrade9: f061Controller.text_Controller324,
                      controllergrade10: f061Controller.text_Controller350,
                      controllergrade11: f061Controller.text_Controller377,
                      controllergrade12: f061Controller.text_Controller404,
                      controllergrade13: f061Controller.text_Controller431,
                      controllergrade14: f061Controller.text_Controller460,
                      controllergrade15: f061Controller.text_Controller487,
                      controllergrade16: f061Controller.text_Controller514,
                      controllergrade17: f061Controller.text_Controller541,
                      controllergrade18: f061Controller.text_Controller568,
                      controllergrade19: f061Controller.text_Controller595,
                      controllergrade20: f061Controller.text_Controller622,
                      controllergrade21: f061Controller.text_Controller649,
                      controllergrade22: f061Controller.text_Controller676,
                      controllergrade23: f061Controller.text_Controller703,
                      controllergrade24: f061Controller.text_Controller730,
                      controllergrade25: f061Controller.text_Controller757,
                      controlleraverage: f061Controller.text_Controller784,
                    ),
                  ],
                ),
                const SizedBox(height: 20),
                Text(
                  'F061-THHC General Consent Form',
                  textAlign: TextAlign.end,
                  style: TextStyle(
                      fontSize: 10,
                      fontWeight: FontWeight.bold,
                      color: Colors.black),
                )
              ],
            ),
          ),
        ),
      )),
    );
  }

  Widget TitleText(String title) {
    return Container(
      padding: const EdgeInsets.symmetric(vertical: 5),
      color: Colors.white,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            title,
            overflow: TextOverflow.ellipsis,
            textAlign: TextAlign.center,
            style: const TextStyle(
                fontWeight: FontWeight.bold, color: Colors.black),
          ),
        ],
      ),
    );
  }

  TableRow buildRowWidget({
    required TextEditingController controllerstaff,
    required TextEditingController controllerbadge,
    required TextEditingController controllerposition,
    required TextEditingController controllergrade1,
    required TextEditingController controllergrade2,
    required TextEditingController controllergrade3,
    required TextEditingController controllergrade4,
    required TextEditingController controllergrade5,
    required TextEditingController controllergrade6,
    required TextEditingController controllergrade7,
    required TextEditingController controllergrade8,
    required TextEditingController controllergrade9,
    required TextEditingController controllergrade10,
    required TextEditingController controllergrade11,
    required TextEditingController controllergrade12,
    required TextEditingController controllergrade13,
    required TextEditingController controllergrade14,
    required TextEditingController controllergrade15,
    required TextEditingController controllergrade16,
    required TextEditingController controllergrade17,
    required TextEditingController controllergrade18,
    required TextEditingController controllergrade19,
    required TextEditingController controllergrade20,
    required TextEditingController controllergrade21,
    required TextEditingController controllergrade22,
    required TextEditingController controllergrade23,
    required TextEditingController controllergrade24,
    required TextEditingController controllergrade25,
    required TextEditingController controlleraverage,
    required Color color,
  }) {
    return TableRow(decoration: BoxDecoration(color: color), children: [
      TextFormField(
        controller: controllerstaff,
      ),
      TextFormField(
        controller: controllerbadge,
      ),
      TextFormField(
        controller: controllerposition,
      ),
      TextFormField(
        controller: controllergrade1,
      ),
      TextFormField(
        controller: controllergrade2,
      ),
      TextFormField(
        controller: controllergrade3,
      ),
      TextFormField(
        controller: controllergrade4,
      ),
      TextFormField(
        controller: controllergrade5,
      ),
      TextFormField(
        controller: controllergrade6,
      ),
      TextFormField(
        controller: controllergrade7,
      ),
      TextFormField(
        controller: controllergrade8,
      ),
      TextFormField(
        controller: controllergrade9,
      ),
      TextFormField(
        controller: controllergrade10,
      ),
      TextFormField(
        controller: controllergrade11,
      ),
      TextFormField(
        controller: controllergrade12,
      ),
      TextFormField(
        controller: controllergrade13,
      ),
      TextFormField(
        controller: controllergrade14,
      ),
      TextFormField(
        controller: controllergrade15,
      ),
      TextFormField(
        controller: controllergrade16,
      ),
      TextFormField(
        controller: controllergrade17,
      ),
      TextFormField(
        controller: controllergrade18,
      ),
      TextFormField(
        controller: controllergrade19,
      ),
      TextFormField(
        controller: controllergrade20,
      ),
      TextFormField(
        controller: controllergrade21,
      ),
      TextFormField(
        controller: controllergrade22,
      ),
      TextFormField(
        controller: controllergrade23,
      ),
      TextFormField(
        controller: controllergrade24,
      ),
      TextFormField(
        controller: controllergrade25,
      ),
      TextFormField(
        controller: controlleraverage,
      ),
    ]);
  }
}
